spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/agvanetta/configs_microservices
          default-label: main
        #native:
          #search-locations: classpath:/config

server:
  port: 8888
